execute_process(
  COMMAND ${CMAKE_COMMAND} --build ${CMAKE_CURRENT_BINARY_DIR} --target package_source
  WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR} 
  )
file(
  INSTALL ${CMAKE_PROJECT_NAME}.tar.gz 
  DESTINATION ${CMAKE_INSTALL_PREFIX}/src
  )
