version: 2.1

# Anchors in case we need to override the defaults from the orb
#baselibs_version: &baselibs_version v8.7.0
#bcs_version: &bcs_version v12.0.0

orbs:
  ci: geos-esm/circleci-tools@5

workflows:
  build-test:
    jobs:
      # Build GEOSgcm
      - ci/build:
          name: build-GEOSgcm-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler: [gfortran, ifort, ifx]
          #baselibs_version: *baselibs_version
          repo: GEOSgcm
          checkout_fixture: true
          # V12 code uses a special branch for now.
          fixture_branch: feature/sdrabenh/gcm_v12
          develop_repos: "GEOSgcm_GridComp GEOSgcm_App GMAO_Shared FVdycoreCubed_GridComp fvdycore"
          # We comment out this as it will "undo" the fixture_branch
          #mepodevelop: true
          persist_workspace: true # Needs to be true to run fv3/gcm experiment, costs extra

      # Run AMIP GCM (1 hour, no ExtData)
      - ci/run_gcm:
          name: run-GCM-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler: [gfortran, ifort, ifx]
          requires:
            - build-GEOSgcm-on-<< matrix.compiler >>
          repo: GEOSgcm
          #baselibs_version: *baselibs_version
          #bcs_version: *bcs_version

      # Run Coupled GCM (1 hour, no ExtData)
      - ci/run_gcm:
          name: run-coupled-GCM-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler: [ifort]
              # There seems to be an issue with gfortran, mom6, and GNU
              # Also ifx doesn't work either
          requires:
            - build-GEOSgcm-on-<< matrix.compiler >>
          repo: GEOSgcm
          #baselibs_version: *baselibs_version
          #bcs_version: *bcs_version
          gcm_ocean_type: MOM6
          change_layout: false
